### ISSUE TITLE
[Question] flask-RESTful or flask-restplus

### ISSUE THREAD

**Issue by chari8** [apryor6/flask_accepts#1]
Hi!
I am using `flask_accepts` together with `flask_restplus`.
To do so, I need to change some code of this library.
My question is that, with which is this library intended to be used, `flask_RESTful` or `flask_restplus` ?

**Comment by apryor6** [comment]
It should work with both. Could you be more specific about what changes were necessary?

**Comment by chari8** [comment]
I made 2 changes to decorators.py
I changed the first line to

```decorators.py
from werkzeug.wrappers import Response
```

This is because the original code raised `import error`.
[commit log](https://github.com/chari8/flask_accepts/commit/2e5dcf4c1749320c8505816fd18bb4f84f273a7a)

And then, line 22

```decorators.py
from flask_restplus import reqparse
```
This is also due to `import error`.
[commit log](https://github.com/chari8/flask_accepts/commit/19a2f6be7faf1dc74c13743a65f07ad0de434903)

Thansks.

**Comment by apryor6** [comment]
Thanks. Updated
