### ISSUE TITLE
Intercept and correct input type `bool` in reqparse dicts

### ISSUE THREAD

**Issue by apryor6** [apryor6/flask_accepts#14]
See [this issue](https://github.com/noirbizarre/flask-restplus/issues/199) for a discussion around how RESTplus parses the string "false" as true with `type=bool`. 

We can fix this by intercepting the boolean parameter in the dicts that are being passed in `@accepts` or `@reponds` and casting them to `flask_restplus.inputs.boolean`

**Comment by rcsm** [comment]
Hey @apryor6 ! I'd like to claim this one. Just a question : I've noticed you used a function called `isistance(arg, some_type)`. I'm thinking about using `type(arg) == bool`. Do you think there would be some problem with that?

**Comment by apryor6** [comment]
`isinstance` should be preferred when checking the type of an object because it will also, in general, check subclasses of the type. In this specific case, it so happens that `bool` cannot be subclassed, but for consistency and readability `isinstance` is better.

**Comment by rcsm** [comment]
I have a question: how can I run the tests locally? I mean, I've created a test and did the change, but now I'd like to test it locally, to get it to fail and then pass before running in circle ci.

**Comment by apryor6** [comment]
First install pytest (`pip install pytest`), and then run `pytest`

There’s a pytest.ini file at the root source directory that configures pytest for you

**Comment by rcsm** [comment]
PR is done: #22 .

**Comment by apryor6** [comment]
Available in [0.10.1](https://github.com/apryor6/flask_accepts/releases/tag/v0.10.1)
