### ISSUE TITLE
Simple Example in README.md looks incorrect

### ISSUE THREAD

**Issue by martinpeck** [apryor6/flask_accepts#29]
README.md contains the following example, but it looks to me like there are some issues with this code. I'd fix it, but I'm not 100% sure what the best fix is. Happy to raise a PR if you're able to point me in the right direction.

The code looks like this...

```python
from flask import Flask, request
from flask_accepts import accepts, responds

from .widget import Widget, WidgetSchema, make_widget

def create_app():
    app = Flask(__name__)

    @app.route("/widget")
    @accepts(dict(name="foo", type=str), api=api)
    @responds(schema=WidgetSchema, api=api)
    def widget()
        name: str = request.parsed_args["foo"]
	widget: Widget = make_widget(name)
	return widget

    return app
```

Issues:

- the `def widget()` is missing the `:`. Easy fix.
- the `@accepts` decorator uses `api` but this isn't defined within this code. Is the fix to remove this from the decorator?
- the `@responds` decorator has same issue. Same fix?

**Comment by apryor6** [comment]
Thanks! You're correct on all counts
