### ISSUE TITLE
Adding descriptions to fields

### ISSUE THREAD

**Issue by optlink** [apryor6/flask_accepts#33]
Flask-RESTPlus has the ability to set field descriptions that appear in swagger like so:
https://flask-restplus.readthedocs.io/en/stable/swagger.html#documenting-the-fields
Is something like this possible in flask_accepts with marshmallow? I can't find anything in the documentation and a quick glance over the flask_accepts source indicates that any "metadata" set on a marshmallow field is ignored during the mapping process. I imagine that something like this would be ideal:
```
from marshmallow import Schema, fields

class SomeSchema(Schema):
    some_field = fields.String(metadata={"description":"Some Field"})
```

Reference for marshmallow field metadata: https://marshmallow.readthedocs.io/en/stable/api_reference.html#module-marshmallow.fields

Any ideas?

**Comment by apryor6** [comment]
Knee jerk reaction is there is no reason this can’t or shouldn’t be done, so I’ll give it a whirl sometime next week if possible. Thanks!
