### ISSUE TITLE
Wierd model names after version 0.12.0

### ISSUE THREAD

**Issue by edkb** [apryor6/flask_accepts#35]
Model names are showing _load_ and _dump_ extensions after version 0.12.x
```
class CogSchema(Schema):
    cog_foo = fields.String(default="cog")
    cog_baz = fields.Integer(default=999)


class WidgetSchema(Schema):
    foo = fields.String(default="test string")
    baz = fields.Integer(default=42)
    flag = fields.Bool(default=False)
    date = fields.Date(default="01-01-1900")
    dec = fields.Decimal(default=42.42)
    dct = fields.Dict(default={"key": "value"})

    cog = fields.Nested(CogSchema)


@api.route("/restplus/make_a_widget")
class WidgetResource(Resource):
    @accepts(dict(name="some_arg", type=str), schema=CogSchema, api=api)
    @responds(schema=CogSchema, api=api)
    def get(self):
        return request.parsed_obj

    @accepts(dict(name="some_arg", type=str), schema=WidgetSchema, api=api)
    @responds(schema=WidgetSchema, api=api)
    def post(self):
        return request.parsed_obj
```
![image](https://user-images.githubusercontent.com/12564798/65049567-517e2f00-d93c-11e9-9f71-587de2724bd4.png)

**Comment by apryor6** [comment]
This was introduced [here](https://github.com/apryor6/flask_accepts/pull/31) to handle certain options within Marshmallow.

The code could be modified to only append these words to the model name if you are using these keywords. I think I would prefer it this way as the model names will be simpler for most use cases. Thoughts?

**Comment by edkb** [comment]
Well, since these options are related to specific attributes of the model I think it shouldn't affect the model name at all.

**Comment by apryor6** [comment]
The trouble is that Swagger does not differentiate between or otherwise annotate the fields as load or dump only.. that concept only exists in Marshmallow. Thus one solution is to have two models if you provide load_only or dump_only.

Again, I agree that the munged names are annoying
