### ISSUE TITLE
Missing 'required', 'description', 'default' parameters in Restplus field initialisation.

### ISSUE THREAD

**Issue by AndreyKis** [apryor6/flask_accepts#36]
Restplus provides opportunity to specify if a field in a model is **required** or not. It also has per-field **description**, **default** parameters and other interesting documentation features.

Unfortunately, most of this functionality is not yet supported by flask_accepts, while it might be super-useful for end users to see such information in docs (alongside with fields description, which already has an opened issue #33 ). So I would be happy to participate in developing those features.

As far as I understood, missing 'description, 'required'  and other parameters can be fully fixed by modifying 

> flask_accepts/utils

 _type_map_ variable.

I can submit PR with this function:

```
def _ma_field_to_fr_field(value, model_name) -> dict:
    fr_field_parameters = {}

    if hasattr(value, 'default'):
        fr_field_parameters['example'] = value.default

    if hasattr(value, 'required'):
        if isinstance(value.required, bool) is False:
            raise TypeError(
                "Wrong type for 'required' parameter in marshmallow schema field. Model: {}, field: {}".format(
                    model_name, value.name
                )
            )

        fr_field_parameters['required'] = value.required

    if hasattr(value, 'metadata') and 'description' in value.metadata:
        fr_field_parameters['description'] = value.metadata['description']

    if hasattr(value, 'missing') and type(value.missing) != ma.utils._Missing:
        fr_field_parameters['default'] = value.missing

    return fr_field_parameters
```

It can be applied in every mapper function, used to map marshmallow field type to restplus field type in this way:

```
ma.Bool: lambda val, api, model_name, operation: fr.Boolean(
        **_ma_field_to_fr_field(val, model_name)
),
```

It should also be applied to Nested and List types in the same way:
```
fr.List(
        map_type(val.inner, api, model_name, operation), **_ma_field_to_fr_field(val, model_name)
)
fr.Nested(
        map_type(val.nested, api, model_name, operation), **_ma_field_to_fr_field(val, model_name)
)
```

It can later be used to parse marshmallow model fields for Range validator with min / max being present. This might be useful as restplus allows to specify min / max values for List, String, Float and other types.

The result documentation for models would look like this:
![Screen Shot 2019-09-24 at 13 40 07](https://user-images.githubusercontent.com/11021559/65512320-e058f180-ded0-11e9-92e5-df32c6bf80e0.png)

For comparison, without this fix, documentation for same model would look like this:
![Screen Shot 2019-09-24 at 13 41 14](https://user-images.githubusercontent.com/11021559/65512388-01214700-ded1-11e9-840b-b7d61bbbc4fa.png)

If this whole thing makes sense to lead developers on this project, I am happy to add some tests to new functionality and submit PR by the end of today.

**Small Note:** I have been working with restplus a lot in scope of my current project at work. Unfortunately, me and my team realised restplus limits us too much in terms of model parsing. That is why we decided to move to Marshmallow. However, we want to keep documentation and are planning to use flask_accepts to do so. That is why I will be happy to submit other changes in future.

**Comment by apryor6** [comment]
This sounds like a substantial improvement, and I would happily accept a reviewed PR that provides tests. 

This would also address issue #33.

Also, regarding your team running into limitations between RESTplus and Marshmallow -- this is _precisely_ the same pain I had that led to this project. I would welcome the additional contributors.

**Comment by apryor6** [comment]
Some quick notes as there is not yet a formal contribution guide:

- Test coverage as measured by Codecov via CircleCI should not change
- Black is used for formatting
- Pylint score is used for linting, though this check is not actually in place as of yet

**Comment by AndreyKis** [comment]
Great, thank you!
Will try to submit PR by the end of today after ensuring to comply with requirements you've mentioned.
