### ISSUE TITLE
marshmallow's (>=3.0.0b7) load method has only one output

### ISSUE THREAD

**Issue by nadwir** [apryor6/flask_accepts#5]
Hi,
I tried to use the decorator @accepts with a marshmallow schema, but there is an error:

File "/XXX/YYY//site-packages/flask_accepts/decorators/decorators.py", line 80, in inner
    obj, err = schema(many=many).load(request.get_json())
ValueError: too many values to unpack (expected 2)

I think, this is because marshmallow's schema.load returns from version 3.0.0b7 only one parameter, not two (https://marshmallow.readthedocs.io/en/stable/upgrading.html).

Is there any way to cover this?

**Comment by apryor6** [comment]
Thanks, this was resolved by #10
