### ISSUE TITLE
Update dev-requirements.txt

### ISSUE THREAD

**Issue by michaelbukachi** [apryor6/flask_accepts#56]
Hi, great library.
There's a typo in `dev-requirement.txt` , flask-restx version is `flask-restx==0.12.1`, which doesn't exist.

**Comment by apryor6** [comment]
Thanks, I have updated the version accordingly (flask-restx was forked from flask-RESTplus, but I obviously missed updating the version, good catch). I did not bump the release on PyPi as this only affects users cloning the repo itself.
