### ISSUE TITLE
Add supported versions to readme and/or pypi

### ISSUE THREAD

**Issue by michaelbukachi** [apryor6/flask_accepts#57]
Hi.
After cloning the project and installing requirements, I tried to run the tests only for them to fail. I then realized that this library uses `dataclasses` which is a python >= 3.8 feature. Would be nice to add this information to the README file. It would really help with those interested in contributing :sweat_smile:.

**Comment by apryor6** [comment]
Thanks, I have [updated the README](https://github.com/apryor6/flask_accepts/blob/master/README.md#installation)
