### ISSUE TITLE
The X-Fields header is ignored

### ISSUE THREAD

**Issue by volfpeter** [apryor6/flask_accepts#58]
Hi,

The handling of the `X-Fields` header (or the `app.config["RESTX_MASK_HEADER"]` header to be more precise) is ignored when response marshaling is done using a `mashmallow` schema.

I have already implemented the bug fix, PR is coming soon.

All the best!

**Comment by apryor6** [comment]
The best kind of issues are the ones that come with promise of a fix at the same time! Looking forward to it.

**Comment by apryor6** [comment]
Available on pypi 0.16.2
