### ISSUE TITLE
Feature: accept dictionaries as schemas

### ISSUE THREAD

**Issue by volfpeter** [apryor6/flask_accepts#60]
Hi,

Just for the sake of completeness, the `accepts` and `responds` decorators should accept dictionaries (with a `model_name` argument) as a schema. To achieve this, `model_name` could be passed on to `_get_or_create_schema()` from the decorators and the method should be extended with this bit of code:

```python
if isinstance(schema, dict):
    if model_name is None:
        raise ValueError(
            "You should set model_name when the schema is generated from a dict."
        )
    schema = Schema.from_dict(schema, name=model_name)
```

I can send a PR if the feature request is accepted.

Br,

**Comment by apryor6** [comment]
The trouble here is that dictionaries provided to these decorators are treated as query parameters for `reqparse`, see [code here](https://github.com/apryor6/flask_accepts/blob/3e384aa05336ef5a9c6d8678cad3a5d67dac4533/flask_accepts/decorators/decorators.py#L51-L63)

**Comment by volfpeter** [comment]
Oh, I see, I've missed that. Feel free to reject the issue then.
