### ISSUE TITLE
Usage with flask_marschmallow (with optional flask_sqlalchemy and marshmellow-sqlalchemy)

### ISSUE THREAD

**Issue by IamSAB** [apryor6/flask_accepts#61]
A short question: 

Is it possible to use the two decorators `@accepts` and `@responds` with schemas defined with [flask_marshmellow](https://flask-marshmallow.readthedocs.io/en/latest/) including the optional integration with [flask_sqlalchemy](https://flask-sqlalchemy.palletsprojects.com/en/2.x/) and [marshmellow-sqlalchemy](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/)?

That way, I could connect marshmallow schemas with models from sqlalchemy and still use your decorators to save some line of codes including swagger documentation.

I pose this question, as I don't see exactly, how you use marshmallow under the hood.

Thanks

**Comment by apryor6** [comment]
Yes this works and is actually how I use the library myself, as those schemas are not really anything special/different from the “core” marshmallow schemas. The part that flask marshmallow adds is the context set up and tear down associated with flask and the database context.
