### ISSUE TITLE
Support for higher flask-restx versions ?

### ISSUE THREAD

**Issue by pipozzz** [apryor6/flask_accepts#68]
I'm getting error in my new project using latest flask-restx

`flask-accepts 0.16.2 has requirement flask-restx==0.1.0, but you'll have flask-restx 0.2.0 which is incompatible.`

Are you going to support multiple versions instead of flask-restx==0.1.0?

Thanks

**Comment by amickael** [comment]
I'm using flask_accepts with flask-restx 0.2.0 without any issues. I do not believe there were any changes in restx that would have broken compatibility with the current version of accepts: https://github.com/python-restx/flask-restx/releases/tag/0.2.0

**Comment by pipozzz** [comment]
When I did pip -U -r requirements.txt I got this warning: 
`flask-accepts 0.16.2 has requirement flask-restx==0.1.0, but you'll have flask-restx 0.2.0 which is incompatible.
` 
and this is caused by this :

https://github.com/apryor6/flask_accepts/blob/3e384aa05336ef5a9c6d8678cad3a5d67dac4533/setup.py#L15

If there is no compatibility issue I suggest to change it to 

> "flask-restx>=0.1.0"

**Comment by apryor6** [comment]
Thanks, this has been addressed and is now available on pypi in flask_accepts 0.16.3
