### ISSUE TITLE
[Q] Customize schema_errors?

### ISSUE THREAD

**Issue by yujinyuz** [apryor6/flask_accepts#82]
Currently, when I send a post request with invalid data, I'm getting this response

```json
{
    "schema_errors": {
        "email": [
            "Not a valid email address."
        ],
        "password": [
            "Missing data for required field."
        ]
    }
}
```

Is it possible to customize it such that it appears something like this?

```json
{
    "message": "Problem occurred",
    "errors": {
        "email": [
            "Not a valid email address."
        ],
        "password": [
            "Missing data for required field."
        ]
    }
}
```

```

**Comment by scompt** [comment]
I think you can handle this at the Marshmallow Schema level by overriding the [`handle_error`](https://marshmallow.readthedocs.io/en/stable/extending.html#custom-error-handling) method.

**Comment by yujinyuz** [comment]
@scompt Thanks! But yeah, I have resolved this by overriding the error handlers. I was just thinking that maybe there is a specific way for flask-accepts to be able to override this.

Anyway, this can be closed
